In [216]:
import numpy as np
np.set_printoptions(formatter={'float_kind':'{:.3f}'.format})

In [217]:
# problem setup
left = np.array([3,4]).reshape(-1,1)
up = np.array(np.arange(0,6))

In [218]:
# problem formulation
simplex = np.array([[2.0,3.0,2.0,1.0,0.0,0.0,1000.0],[1.0,1.0,2.0,0.0,1.0,0.0,800.0],[-7.0,-8.0,-10.0,0.0,0.0,1.0,0.0]])

In [219]:
simplex

array([[2.000, 3.000, 2.000, 1.000, 0.000, 0.000, 1000.000],
       [1.000, 1.000, 2.000, 0.000, 1.000, 0.000, 800.000],
       [-7.000, -8.000, -10.000, 0.000, 0.000, 1.000, 0.000]])

In [220]:
while(True):
    arr = simplex[-1][simplex[-1]<0]
    
    if len(arr) == 0 :
        break 
    
    col = np.argmin(simplex[-1])
    row = np.argmin(simplex[:-1,-1]//simplex[:-1,2])
    left[row] = col
    
    simplex[row] = simplex[row]/simplex[row,col]
    pivot_col = simplex[:,col]
    row_indexes = np.where(pivot_col!=simplex[row,col])[0]
    for i in row_indexes:
        factor = simplex[i,col]/simplex[row,col]
        simplex[i] = simplex[i] - factor*simplex[row]
        print(simplex)

[[1.000 2.000 0.000 1.000 -1.000 0.000 200.000]
 [0.500 0.500 1.000 0.000 0.500 0.000 400.000]
 [-7.000 -8.000 -10.000 0.000 0.000 1.000 0.000]]
[[1.000 2.000 0.000 1.000 -1.000 0.000 200.000]
 [0.500 0.500 1.000 0.000 0.500 0.000 400.000]
 [-2.000 -3.000 0.000 0.000 5.000 1.000 4000.000]]
[[0.500 1.000 0.000 0.500 -0.500 0.000 100.000]
 [0.250 0.000 1.000 -0.250 0.750 0.000 350.000]
 [-2.000 -3.000 0.000 0.000 5.000 1.000 4000.000]]
[[0.500 1.000 0.000 0.500 -0.500 0.000 100.000]
 [0.250 0.000 1.000 -0.250 0.750 0.000 350.000]
 [-0.500 0.000 0.000 1.500 3.500 1.000 4300.000]]
[[1.000 2.000 0.000 1.000 -1.000 0.000 200.000]
 [0.000 -0.500 1.000 -0.500 1.000 0.000 300.000]
 [-0.500 0.000 0.000 1.500 3.500 1.000 4300.000]]
[[1.000 2.000 0.000 1.000 -1.000 0.000 200.000]
 [0.000 -0.500 1.000 -0.500 1.000 0.000 300.000]
 [0.000 1.000 0.000 2.000 3.000 1.000 4400.000]]


In [221]:
left.ravel()

array([0, 2])

In [222]:
simplex[:,-1]

array([200.000, 300.000, 4400.000])